### ISSUE TITLE
Error while running the example file

### ISSUE THREAD

**Issue by PranjalBiswas** [RMonica/rviz_cloud_annotation#3]
Hi,

I am very new to Linux and to ROS. I was trying to run the rviz_cloud_annotation tool to label my point cloud data with 3D boundng boxes. After downloading and extracting the github repository, I tried to run the following command as suggested:

roslaunch rviz_cloud_annotation example.launch

But I get the following error:

[example.launch] is neither a launch file in package [rviz_cloud_annotation] nor is [rviz_cloud_annotation] a launch file name
The traceback for the exception was written to the log file

Also, I had already installed ROS Kinetic, PCL 1.8 along with CUDA 8.0 and cudnn 6.0 before running the command above. What exactly I am doing wrong? Thanks a lot in advance.

**Comment by RMonica** [comment]
Hi.

Did you create the workspace properly? (see [ROS tutorials](http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment))
Did you ``source`` it?
Did you compile the workspace with ``catkin_make`` (or ``catkin build``, if you can use it)?
Did you re-``source`` the workspace after compilation?

CUDA is not required.
If you can start RViz, the minimum graphics requirements for the annotation tool are satisfied, since the tool does not display anything by itself.
However, if you want some responsiveness, you should have a video card driver installed.

Note that the tool does not support annotation based on 3D bounding boxes.
